version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout

  file_users:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: "./logs/users.log"

  file_messages:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: "./logs/messages.log"

  file_products:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: "./logs/products.log"

loggers:
  users:
    level: DEBUG
    handlers: [console, file_users]
    propagate: false
  
  messages:
    level: DEBUG
    handlers: [console, file_messages]
    propagate: false

  products:
    level: DEBUG
    handlers: [console, file_products]
    propagate: false

root:
  level: WARNING
  handlers: [console]
